/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData calendar_edit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_tasks = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_up = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_down = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule_edit = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_left = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_right = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
